Bootstrap requests_queue service
dod-ccpo/requests-queue pull request #1
Opened 2018-06-05 19:43 UTC by richard-dds

Set up the `requests_queue` service, as a tornado app, making use of the conventions we've established so far. `scripts/`, `pipenv`, `.ini` config.

Also made a mock `requests/` endpoint with the data I saw in the spreadsheet, though now I'm wondering if that was the right place to put it.

2018-06-05 20:13 UTC, jordangov requested changes

2018-06-05 20:13 UTC, jordangov commented on README.md
> +# ATST
Uuuh... looks like we copied a bunch of stuff? I'm guessing we don't want the title, build status, etc from ATST.

2018-06-05 20:13 UTC, jordangov commented on requests_queue/handlers/request.py
> +request = {
Sorry, why is this here? I'm unclear why we have stub data in our request handler.

2018-06-06 20:51 UTC, richard-dds commented on requests_queue/handlers/request.py
> +request = {
Removed, though I'm not sure what the issue was with it. Updated the handler to return an empty response.

2018-06-06 20:51 UTC, richard-dds commented on README.md
> +# ATST
👍

2018-06-07 02:16 UTC, jordangov approved these changes

2018-06-07 12:22 UTC, bduggan commented
Looks good! 👍

2018-06-07 12:22 UTC, briandds approved these changes
Looks good!

2018-06-07 13:57 UTC, merged